# Generated by Django 3.0.4 on 2020-03-13 07:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Tods',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Title', models.CharField(max_length=200)),
                ('details', models.CharField(max_length=500)),
                ('do_date', models.DateTimeField(verbose_name='date published')),
            ],
        ),
    ]
