# Generated by Django 3.0.4 on 2020-03-13 08:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0002_auto_20200313_0812'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='tods',
            options={'verbose_name_plural': 'Todss'},
        ),
    ]
